version: '3'
services:
  rails1:
    build: .
    ports:
      - "3000:80"
    volumes:
      - ./:/var/www/blockchain
  rails2:
    build: .
    ports:
      - "3001:80"
    volumes:
      - ./:/var/www/blockchain
  curl:
    image: byrnedo/alpine-curl
